# Generated by Django 5.1.5 on 2025-01-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='codigo',
            new_name='habitacion',
        ),
    ]
